#!/usr/bin/env bash
# Bash script that transfers a filefrom our client to server
# the script takes in 4 parameters
# 1.  FILE_PATH="$1"
# 2.  SERVER_IP="$2"
# 3.  USERNAME="$3"
# 4.  SSH_KEY="$4"

if [ "$4" ]; then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
elif [ "$3" ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
