#!/usr/bin/env bash
#This is a Bash script that displays the following;
	# To infinity and beyond indefinitely
	# Has sleep 2 between each iteration
	# I am invincible when receiving a SIGTERM signal

while true
do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "I am invincible!!!"' SIGTERM
done
