#!/usr/bin/env bash
# A Bash script that displays the contents of a the file /etc/passwd
# From the file it only displays: The username, user id and Home directory path for the user

lines=0
while [ $lines -lt 2 ]
do
	cut -d ":" -f 1,3,6 /etc/passwd
	(( lines++ ))
done
