#!/usr/bin/env bash
# Bash script that first displays No from 1 - 20
	# On the 4 iteration displays 4 and then bad luck from China
	# On the 9 iteration displays 9 and then bad luck from Japan
	# On the 17 iteration displays 17 and then bad luck from Italy

num=1

while [ $num -le 20 ]
do
	echo "$num"

	case $num in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((num++))
done
