#!/usr/bin/env bash
# A script that displays the time of 12 hours and 59 min
	# It displays hours from 0 - 12
	# Displays minutes from 1 - 59

num_of_hours=0
while [ $num_of_hours -le 12 ]
do
	echo "Hour: $num_of_hours"

	minutes=1
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		((minutes++))
	done

	((hour++))
done
