#!/usr/bin/env bash
# Confirguring Nginx to run as Nginx user and making it listen at port 8080

pkill apache2
sed -i "s/listen 80/listen 8080/g" /etc/nginx/sites-available/default
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
